#!/usr/bin/env bash

# ---
# IMPORTANT: Use the following statement at the TOP OF EVERY TEST SCRIPT
#            to ensure that this package's 'bin/' subfolder is added to the path so that
#            this package's CLIs can be invoked by their mere filename in the rest
#            of the script.
# ---
PATH=${PWD%%/test*}/bin:$PATH

# Helper function for error reporting.
die() { (( $# > 0 )) && echo "ERROR: $*" >&2; exit 1; }

out=$(whichpm File::Spec) || die  # should succeed

pathFragment='/File/Spec.pm'
[[ $out =~ "$pathFragment"$ ]] || die "Expected '$pathFragment' in output."

# -- With -v, look for core-status indicator

coreStatusIndicator='core>='
whichpm -v File::Spec | grep -Fq $'\t'"$coreStatusIndicator"  || die "Expected core-status indicator '$coreStatusIndicator' in output."

exit 0
