#!/usr/bin/env bash

# ---
# IMPORTANT: Use the following statement at the TOP OF EVERY TEST SCRIPT
#            to ensure that this package's 'bin/' subfolder is added to the path so that
#            this package's CLIs can be invoked by their mere filename in the rest
#            of the script.
# ---
PATH=${PWD%%/test*}/bin:$PATH

# Helper function for error reporting.
die() { (( $# > 0 )) && echo "ERROR: $*" >&2; exit 1; }

# Inspecting Data::Dumper without -a normally generates a warning, due
# to our dummy duplicate in ./Data/Dumper.pm
# -q should silence that.
errOut=$(whichpm -q Data::Dumper 2>&1 1>/dev/null) || die

[[ -z $errOut ]] || die "Expected no stderr output, got '$errOut'."

exit 0

